name: taco-helps
favicon: null
layout_spectrum: 0.051675269613042474
typography_spectrum: 0.10954
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.125
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
